/**
 * 기관별 공문서 서식 실측값 — 자동 생성 파일, 고치지 말 것 (scripts/build-agency-styles.mjs).
 *
 * 원천: UpstageAI/korean-report-hwpx @8076607 (MIT, THIRD_PARTY/korean-report-hwpx.LICENSE) — 정책브리핑 보도자료 HWPX
 * 2,670건(52개 중앙행정기관) 전수 파싱. report = 보도자료 참고·붙임 구간(보고서형, 1,326건)의 계층별 글꼴·크기와
 * 표 머리, press = 보도자료 본문, band = 참고·붙임 쪽 머리 표 라벨 칸 색(11,338건). null 은 그 기관 표본이 모자라
 * 원천에 규칙이 없는 항목(공통값을 쓴다). levels 는 □·ㅇ·- 순, 굵기는 원천에 없어 보통으로 그린다(원 저장소 렌더와 같음).
 */

export interface AgencyFont { font: string; pt: number }
export type AgencyBullet2 = "ㅇ" | "○" | "◦" | "❍"

export interface AgencyReportStyle {
  /** 규칙을 산출한 문서 수 */
  docs: number
  levels: [AgencyFont, AgencyFont, AgencyFont]
  note: AgencyFont
  ref: AgencyFont
  p: AgencyFont
  bullet2: AgencyBullet2
  table: { font: string; pt: number; fill: string }
}

export interface AgencyPressStyle {
  /** 규칙을 산출한 본문 문단 수 */
  paras: number
  /** 본문 방식 — para: 기호 없는 기사체 문단 위주, box: □ → ㅇ 개조식 */
  style: "para" | "box"
  /** 그 방식 문단의 비율 */
  share: number
  levels: [AgencyFont, AgencyFont, AgencyFont]
  note: AgencyFont
  p: AgencyFont
  bullet2: AgencyBullet2
}

export interface AgencyStyle {
  report: AgencyReportStyle | null
  press: AgencyPressStyle | null
  band: { fill: string | null; text: string } | null
}

export const AGENCY_COMMON: AgencyStyle = {"report":{"docs":1129,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":32253,"style":"para","share":0.37,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}}

export const AGENCY_STYLES: Record<string, AgencyStyle> = {
  "개인정보보호위원회": {"report":{"docs":10,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"HY궁서","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":10,"fill":"#F2F2F2"}},"press":{"paras":455,"style":"para","share":0.17,"levels":[{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":null,"text":"#000000"}},
  "경찰청": {"report":{"docs":4,"levels":[{"font":"휴먼명조","pt":15},{"font":"문체부 바탕체","pt":15},{"font":"문체부 바탕체","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"◦","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":332,"style":"para","share":0.06,"levels":[{"font":"바탕","pt":14},{"font":"문체부 바탕체","pt":14},{"font":"바탕","pt":14}],"note":{"font":"한양중고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#E7F4F6","text":"#000000"}},
  "고용노동부": {"report":{"docs":65,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":13},"p":{"font":"휴먼명조","pt":12},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":2104,"style":"para","share":0.28,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"한컴바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"한컴바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#193657","text":"#FFFFFF"}},
  "공정거래위원회": {"report":{"docs":29,"levels":[{"font":"휴먼명조","pt":14},{"font":"한양신명조","pt":14},{"font":"한양신명조","pt":14}],"note":{"font":"한양중고딕","pt":12},"ref":{"font":"한양중고딕","pt":12},"p":{"font":"신명 견명조","pt":18},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":977,"style":"para","share":0.28,"levels":[{"font":"휴먼명조","pt":14},{"font":"한양신명조","pt":14},{"font":"한양신명조","pt":14}],"note":{"font":"한양중고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "과학기술정보통신부": {"report":{"docs":47,"levels":[{"font":"함초롬바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":14},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":1365,"style":"para","share":0.27,"levels":[{"font":"함초롬바탕","pt":15},{"font":"휴먼명조","pt":13},{"font":"휴먼명조","pt":13}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#2B2D63","text":"#FFFFFF"}},
  "관세청": {"report":{"docs":12,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"휴먼명조","pt":10},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":10},"bullet2":"◦","table":{"font":"한양중고딕","pt":12,"fill":"#F2F2F2"}},"press":{"paras":587,"style":"para","share":0.29,"levels":[{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":null,"text":"#000000"}},
  "교육부": {"report":{"docs":34,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":12},"bullet2":"◦","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":654,"style":"para","share":0.46,"levels":[{"font":"함초롬바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"함초롬바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":14},"bullet2":"◦"},"band":{"fill":"#DFE6F7","text":"#000000"}},
  "국가교육위원회": {"report":{"docs":3,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"한양신명조","pt":14},"bullet2":"◦","table":{"font":"맑은 고딕","pt":13,"fill":"#F2F2F2"}},"press":{"paras":46,"style":"para","share":0.11,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"한양신명조","pt":14},"bullet2":"◦"},"band":{"fill":"#23236A","text":"#FFFFFF"}},
  "국가데이터처": {"report":{"docs":5,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"ㅇ","table":{"font":"한양중고딕","pt":10,"fill":"#E1E1E1"}},"press":{"paras":1258,"style":"box","share":0.66,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"○"},"band":{"fill":"#333399","text":"#FFFFFF"}},
  "국가보훈부": {"report":{"docs":10,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#F2F2F2"}},"press":{"paras":161,"style":"para","share":0.19,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#0000FF","text":"#FFFFFF"}},
  "국가유산청": {"report":{"docs":30,"levels":[{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":13}],"note":{"font":"한양중고딕","pt":12},"ref":{"font":"한양중고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○","table":{"font":"한양중고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":623,"style":"para","share":0.17,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":13},{"font":"바탕","pt":13}],"note":{"font":"맑은 고딕","pt":11},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "국무조정실": {"report":{"docs":25,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#F0F0F0"}},"press":{"paras":1206,"style":"box","share":0.92,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "국민권익위원회": {"report":{"docs":3,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"맑은 고딕","pt":12},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#FBEFD4"}},"press":{"paras":449,"style":"box","share":0.53,"levels":[{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"HY중고딕","pt":13},"p":{"font":"바탕","pt":15},"bullet2":"ㅇ"},"band":{"fill":"#00468C","text":"#FFFFFF"}},
  "국방부": {"report":{"docs":7,"levels":[{"font":"휴먼명조","pt":16},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"휴먼명조","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"◦","table":{"font":"맑은 고딕","pt":11,"fill":"#ECF2FA"}},"press":{"paras":280,"style":"box","share":0.9,"levels":[{"font":"휴먼명조","pt":16},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":13}],"note":{"font":"맑은 고딕","pt":13},"p":{"font":"한컴바탕","pt":14},"bullet2":"◦"},"band":{"fill":"#193657","text":"#FFFFFF"}},
  "국세청": {"report":{"docs":9,"levels":[{"font":"바탕","pt":14},{"font":"함초롬바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":13},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":13},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":13,"fill":"#E7E7E7"}},"press":{"paras":380,"style":"box","share":0.93,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":15},"bullet2":"ㅇ"},"band":{"fill":"#3E57A5","text":"#FFFFFF"}},
  "국토교통부": {"report":{"docs":35,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":13},"p":{"font":"바탕","pt":12},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#D9D9D9"}},"press":{"paras":1441,"style":"box","share":0.9,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":12},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "금융위원회": {"report":{"docs":13,"levels":[{"font":"바탕","pt":13},{"font":"휴먼명조","pt":13},{"font":"휴먼명조","pt":13}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#FFFFE5"}},"press":{"paras":791,"style":"para","share":0.33,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "기본사회위원회": {"report":null,"press":{"paras":43,"style":"box","share":0.85,"levels":[{"font":"함초롬바탕","pt":14},{"font":"함초롬바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":14},"bullet2":"ㅇ"},"band":null},
  "기상청": {"report":{"docs":18,"levels":[{"font":"휴먼명조","pt":14},{"font":"바탕체","pt":14},{"font":"바탕체","pt":14}],"note":{"font":"돋움체","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"○","table":{"font":"맑은 고딕","pt":9,"fill":"#D1E8FF"}},"press":{"paras":314,"style":"para","share":0.46,"levels":[{"font":"바탕체","pt":14},{"font":"바탕체","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"돋움체","pt":12},"p":{"font":"바탕체","pt":14},"bullet2":"○"},"band":{"fill":"#00468C","text":"#FFFFFF"}},
  "기획예산처": {"report":{"docs":5,"levels":[{"font":"함초롬바탕","pt":14},{"font":"함초롬바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":16},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":422,"style":"para","share":0.19,"levels":[{"font":"함초롬바탕","pt":14},{"font":"함초롬바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#0066FF","text":"#FFFFFF"}},
  "기후에너지환경부": {"report":{"docs":92,"levels":[{"font":"함초롬바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":2042,"style":"para","share":0.39,"levels":[{"font":"함초롬바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "농림축산식품부": {"report":{"docs":54,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":1155,"style":"para","share":0.22,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#0066FF","text":"#FFFFFF"}},
  "농촌진흥청": {"report":{"docs":128,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"한양신명조","pt":15},{"font":"한양신명조","pt":14}],"note":{"font":"한양중고딕","pt":12},"ref":{"font":"한양중고딕","pt":13},"p":{"font":"바탕","pt":14},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":2530,"style":"para","share":0.43,"levels":[{"font":"한양신명조","pt":15},{"font":"한양신명조","pt":15},{"font":"한양신명조","pt":14}],"note":{"font":"돋움","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#1B1760","text":"#FFFFFF"}},
  "문화체육관광부": {"report":{"docs":44,"levels":[{"font":"HY헤드라인M","pt":16},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":11},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":717,"style":"para","share":0.16,"levels":[{"font":"바탕","pt":16},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"바탕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#193657","text":"#FFFFFF"}},
  "방송미디어통신위원회": {"report":{"docs":11,"levels":[{"font":"휴먼명조","pt":15},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":11,"fill":"#D2EBEE"}},"press":{"paras":390,"style":"para","share":0.28,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "방위사업청": {"report":{"docs":6,"levels":[{"font":"휴먼명조","pt":15},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"❍","table":{"font":"맑은 고딕","pt":11,"fill":"#ECF2FA"}},"press":{"paras":164,"style":"para","share":0.22,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"한양중고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"◦"},"band":{"fill":"#1C3D62","text":"#FFFFFF"}},
  "법무부": {"report":{"docs":12,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"❍","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":361,"style":"box","share":0.56,"levels":[{"font":"맑은 고딕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"굴림","pt":13},"p":{"font":"휴먼명조","pt":14},"bullet2":"❍"},"band":{"fill":null,"text":"#000000"}},
  "법제처": {"report":{"docs":3,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#E3E2F2"}},"press":{"paras":105,"style":"para","share":0.17,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"바탕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "병무청": {"report":null,"press":{"paras":39,"style":"para","share":0.37,"levels":[{"font":"함초롬바탕","pt":15},{"font":"함초롬바탕","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"○"},"band":null},
  "보건복지부": {"report":{"docs":78,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":10},"p":{"font":"휴먼명조","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":1725,"style":"para","share":0.33,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕체","pt":14},"bullet2":"○"},"band":{"fill":"#0066FF","text":"#FFFFFF"}},
  "산림청": {"report":{"docs":4,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#DFE6F7"}},"press":{"paras":714,"style":"para","share":0.01,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000066","text":"#FFFFFF"}},
  "산업통상부": {"report":{"docs":16,"levels":[{"font":"함초롬바탕","pt":15},{"font":"함초롬바탕","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#FAFABF"}},"press":{"paras":401,"style":"para","share":0.28,"levels":[{"font":"함초롬바탕","pt":15},{"font":"바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000066","text":"#FFFFFF"}},
  "새만금개발청": {"report":null,"press":{"paras":181,"style":"box","share":0.92,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "성평등가족부": {"report":{"docs":29,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":13},"p":{"font":"휴먼명조","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#F5FCFE"}},"press":{"paras":639,"style":"box","share":0.91,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"함초롬바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":12},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "소방청": {"report":null,"press":{"paras":224,"style":"box","share":0.84,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":null},
  "식품의약품안전처": {"report":{"docs":42,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":13,"fill":"#DFE6F7"}},"press":{"paras":731,"style":"para","share":0.16,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#193657","text":"#FFFFFF"}},
  "외교부": {"report":null,"press":{"paras":443,"style":"para","share":0.03,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"바탕","pt":12}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "우주항공청": {"report":{"docs":20,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"휴먼명조","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":14},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#D9D9D9"}},"press":{"paras":222,"style":"para","share":0.31,"levels":[{"font":"바탕","pt":14},{"font":"함초롬바탕","pt":14},{"font":"함초롬바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#00294B","text":"#FFFFFF"}},
  "원자력안전위원회": {"report":null,"press":{"paras":198,"style":"box","share":0.53,"levels":[{"font":"바탕","pt":15},{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"바탕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#121275","text":"#FFFFFF"}},
  "인구전략위원회": {"report":null,"press":{"paras":82,"style":"para","share":0.5,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":15},"bullet2":"ㅇ"},"band":null},
  "인사혁신처": {"report":{"docs":8,"levels":[{"font":"HY헤드라인M","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":11},"p":{"font":"바탕","pt":15},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#D1DEEF"}},"press":{"paras":315,"style":"para","share":0.05,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#4B72E3","text":"#FFFFFF"}},
  "재외동포청": {"report":null,"press":{"paras":67,"style":"box","share":0.92,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"ㅇ"},"band":null},
  "재정경제부": {"report":{"docs":9,"levels":[{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"HY궁서","pt":18},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#FCF5E7"}},"press":{"paras":513,"style":"para","share":0.2,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#0066FF","text":"#FFFFFF"}},
  "조달청": {"report":{"docs":10,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"한양중고딕","pt":10},"p":{"font":"한양중고딕","pt":12},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#D6D6D6"}},"press":{"paras":353,"style":"para","share":0.03,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"○"},"band":{"fill":"#000066","text":"#FFFFFF"}},
  "중소벤처기업부": {"report":{"docs":23,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":12},"bullet2":"◦","table":{"font":"맑은 고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":529,"style":"para","share":0.21,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"◦"},"band":{"fill":"#DFE6F7","text":"#000000"}},
  "지식재산처": {"report":{"docs":42,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"휴먼명조","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":15},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#FFFFAB"}},"press":{"paras":558,"style":"para","share":0.27,"levels":[{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#2D629C","text":"#FFFFFF"}},
  "질병관리청": {"report":{"docs":32,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":11},"p":{"font":"바탕","pt":14},"bullet2":"○","table":{"font":"맑은 고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":808,"style":"para","share":0.15,"levels":[{"font":"바탕","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15}],"note":{"font":"한양중고딕","pt":13},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#0066FF","text":"#FFFFFF"}},
  "통일부": {"report":null,"press":{"paras":14,"style":"box","share":0.64,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#3A3C84","text":"#FFFFFF"}},
  "해양경찰청": {"report":null,"press":{"paras":40,"style":"box","share":0.57,"levels":[{"font":"바탕","pt":14},{"font":"바탕","pt":14},{"font":"바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":null},
  "해양수산부": {"report":{"docs":31,"levels":[{"font":"맑은 고딕","pt":15},{"font":"한양신명조","pt":14},{"font":"함초롬바탕","pt":14}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"한양신명조","pt":14},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":11,"fill":"#DFE6F7"}},"press":{"paras":652,"style":"para","share":0.34,"levels":[{"font":"휴먼명조","pt":18},{"font":"휴먼명조","pt":18},{"font":"휴먼명조","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"휴먼명조","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
  "행정안전부": {"report":{"docs":52,"levels":[{"font":"HY헤드라인M","pt":15},{"font":"함초롬바탕","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"함초롬바탕","pt":12},"bullet2":"○","table":{"font":"맑은 고딕","pt":12,"fill":"#F2F2F2"}},"press":{"paras":1376,"style":"para","share":0.08,"levels":[{"font":"바탕","pt":15},{"font":"함초롬바탕","pt":15},{"font":"함초롬바탕","pt":15}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"○"},"band":{"fill":"#000066","text":"#FFFFFF"}},
  "행정중심복합도시건설청": {"report":{"docs":9,"levels":[{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":15},{"font":"휴먼명조","pt":13}],"note":{"font":"맑은 고딕","pt":12},"ref":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":13},"bullet2":"ㅇ","table":{"font":"맑은 고딕","pt":12,"fill":"#D9D9D9"}},"press":{"paras":77,"style":"para","share":0.14,"levels":[{"font":"바탕","pt":14},{"font":"휴먼명조","pt":14},{"font":"휴먼명조","pt":13}],"note":{"font":"맑은 고딕","pt":12},"p":{"font":"바탕","pt":14},"bullet2":"ㅇ"},"band":{"fill":"#000080","text":"#FFFFFF"}},
}
